package:
  name: extremelearning
  version: "0.1.1"

source:
  url:  https://github.com/kjhall01/extremelearning/archive/refs/tags/extremelearning-v1.2.tar.gz
build:
  number: 0
  string: extremelearning


requirements:
  host:
    - python>=3.4,<3.9
    - pip
    - setuptools
  run:
    - python>=3.4,<3.9
    - numpy
    - scipy
    - scikit-learn



test:
  imports:
    - extremelearning

about:
  home:
  license: MIT
  summary: 'A selection of ELM-based Machine learning Approaches'
  description: 'Scikit-Learn style ELM Regressors and Classifiers '
  dev_url:  https://github.com/kjhall01/extremelearning/
