package:
  name: pyridl
  version: "0.2.1"

source:
  url:  https://bitbucket.org/hallkjc01/pyridl/get/pyridl-v0.2.1.tar.gz
build:
  number: 0
  string: pyridl


requirements:
  host:
    - python>=3.4,<3.9
    - pip
    - setuptools
  run:
    - python>=3.4,<3.9
    - xarray
    - pathlib
    - dask



test:
  imports:
    - pyridl
    - pyridl.datalibrary_source

about:
  home:
  license: MIT
  summary: 'Pythonic Access to IRI Data Library data'
  description: 'Ever wanted to use IRI DL directly in python? '
  dev_url:  https://bitbucket.org/hallkjc01/pyridl/src/master/
